### PR TITLE
Handle the error message if its returned from the validation function

### PR DESCRIPTION
**Pull request by bradfordben**
Requires https://github.com/2600hz/kazoo-core/pull/19

Handle the new added return type of `{'system_error', {Error, Message}}`

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
@bradfordben it seems that the kzd modules' specs aren't update to date with this error tuple construction. Might need another PR to address that shortcoming.

**Comment by bradfordben** [comment]
> @bradfordben it seems that the kzd modules' specs aren't update to date with this error tuple construction. Might need another PR to address that shortcoming.

Its in the required PR linked in the description as its in core.

**Comment by jamesaimonetti** [comment]
@bradfordben you're right, missed that.

**Comment by bradfordben** [comment]
@jamesaimonetti No problem, thanks for reviewing 👍

**Pull request merged**
