### PR TITLE
Adding config values to allow you to trim media length before sending to an asr provider

### PR DESCRIPTION
**Pull request by bradfordben**
Requires 2600hz/kazoo-core#13

### CODE REVIEW

**Comment by bradfordben** [comment]
Requires https://github.com/2600hz/kazoo-core/pull/13

**Comment by bradfordben** [comment]
Not sure if im doing something wrong to cause to the docs test to fail? Ive run `make apis` and `make docs` from the root kazoo dir and submitted everything in the crossbar dir.

**Comment by mk1s** [comment]
@bradfordben Thank you for submitting this patch and feature, I will review shortly.  

Those CI errors are currently expected within the multi-repo as currently we are having to merge in order when there are dependencies across several repos.   

We are aware and working on this internally, but for the time being we'll merge in order and then rerun the subsequent PRs CI jobs.

In the meantime, if you would please include links to the dependent PRs in your PR summaries, that will create github references we can use to properly track and merge across multiple repos.

**Comment by bradfordben** [comment]
@mk1s Thanks for the reply and clarification around the tests. I will add the links to the summaries for you.

**Pull request merged**
